version: "2"
linters:
  enable:
    - gocritic
    - gosec
    - perfsprint
    - prealloc
    - testifylint
  disable:
    - gochecknoinits
    - nestif
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gochecknoinits
        path: search\.go
      - linters:
          - gosec
        path: search\.go
        text: G404
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
